### ISSUE TITLE
Overwriting main.sh

### ISSUE THREAD

**Issue by ewjoachim** [snok/install-poetry#30]
I might be completely wrong, and if so, I'm very sorry for the noise, but prior to running this action I was skimming through the source code, and realized that if someone happens to have a `main.sh` (or a `get-poetry.sh` but that more uncommon) file at the root of their repository, this action was likely going to overwrite the scripts, then delete them, and break things (albeit just in the CI run). It might be worth copying the script in `/tmp` (or using `mktemp`).

Again, I may well have completely misread the code and if so, I'm sorry, but if I didn't, this may avoid a very very weird and hard-to-debug bug.

☮️ ❤️  and thanks for this action :)

**Comment by sondrelg** [comment]
On reviewing the script, I agree that's probably true haha😊 

Would you be interested in creating a fix?

**Comment by ewjoachim** [comment]
I'm in the middle of something else and I'd like to avoid entering a new rabbit hole at the moment. On the top of my head, I'd say:
```
get_poetry=$(mktemp)
curl ... > $get_poetry
chmod +x $get_poetry
$get_poetry
rm $get_poetry  # or actually skip rm completely, no-one will care
```
(and same for main.sh)

**Comment by sondrelg** [comment]
After a lot of trial and error (because of github actions' terrible debug logging and comments in the yaml not working) I've ended up with more or less exactly what you proposed. 

Feel free to take a look [here](https://github.com/snok/install-poetry/pull/31/files) if you have time, and I'll probably merge this tomorrow at some point 👏

**Comment by sondrelg** [comment]
Thanks again @ewjoachim 😊
