### ISSUE TITLE
Trouble using poetry plugins with poetry 1.1

### ISSUE THREAD

**Issue by connortann** [snok/install-poetry#72]
Hi,

It seems that when Poetry is installed with this action, other plugins such as [poetry-dynamic-versioning](https://github.com/mtkennerly/poetry-dynamic-versioning) do not function as expected. From [this previous issue](https://github.com/mtkennerly/poetry-dynamic-versioning/issues/61), it looks like the extensions do not function when Poetry is installed with `install-poetry.py`.

Hopefully this will all be sorted when the plugin system with Poetry 1.2 is released, but for now it would be good to get poetry extensions working with Poetry 1.1 with this action.

The issue seems to be that if the extensions are installed with e.g. `pip install poetry-dynamic-versioning`, the poetry interpreter cannot see that package. A proposed workaround is to specifically access the pip associated with the poetry install, e.g. `${XDG_DATA_HOME:-~/.local/share}/pypoetry/venv/bin/pip install poetry-dynamic-versioning`.

I haven't seen documentation on what `XDG_DATA_HOME` means. Is this the right pip path to use with this action?

**Comment by sondrelg** [comment]
Do you know if the problem persists if you use the new installation script kept [here](https://github.com/python-poetry/install.python-poetry.org)? I've been meaning to update the curl path to this, so if that resolved this, that would be convenient 😄 

The linux path you're after should otherwise be `/Users/runner/.local/bin/pip` if you install Poetry with this action, on a Github actions ubuntu runner. The installation path is output during the normal installation, so just look for it there 👍 

If you think it's useful, one thing we could do is to add a `POETRY_INSTALLATION_DIR` output to the action that can be accessed in subsequent steps.

**Comment by connortann** [comment]
Thanks, We'll see if we can get it working with that pip path and will let you know.

Yes, I think an output variable would be very useful!

**Comment by sondrelg** [comment]
We've updated the install script for mac and ubuntu runners so suspect this is resolved. Since we already have an open issue for general plugin support I'll close this for now. Feel free to reopen if you're still having problems.
