### ISSUE TITLE
Document the relationship to actions/setup-python poetry caching

### ISSUE THREAD

**Issue by tibbe** [snok/install-poetry#85]
The official actions/setup-python action supports poetry caching (https://github.com/actions/setup-python#caching-packages-dependencies). It would be nice to document how to use this action in combination with that. For example, do they use the same cache directories by default? Should this action be run before or after setup-python?

**Comment by sondrelg** [comment]
Cool, that's a nice new feature then 😊 Would you be interested in opening a PR for this?

**Comment by miigotu** [comment]
You would have to install this like normal, before setup-python and instead of using actions/cache you would set it in the setup-python and remove the actions/cache action. 

Problem is, then poetry is installed using the default runner python, and I'm not sure yet how that works. I have it set just like above and it seems to be working, but I need to print out the python version poetry is using to make sure it's using the right python.

**Comment by sondrelg** [comment]
Closing from inactivity. PRs welcome :slightly_smiling_face:
